- addon/tracked-async-data.ts
- type-tests/tracked-async-data-test.ts
Export a union type as the actual public API of `TrackedAsyncData<T>`, along with a `const`-bound export of the class (with a safe cast for the constructor). The union is implemented as a union of interfaces which extend the base class so that (a) they are guaranteed to be structurally compatible and (b) docstrings continue to "just work".
The upshot of this change: All existing invocations continue to work exactly as they have up to this point, but the type now correctly narrows when checking any of the boolean properties exposed to indicate the state of the type. For example, given a `TrackedAsyncData<string>`, the `.value` and `.error` properties will have the type `null` when `.isPending` is `true`; `.value` will have the type `string` when `.isResolved` is `true` but `.error` will …
> Improve type robustness for `TrackedAsyncData<T>`

- README.md
It seems that `.data` isn't the correct way access the asynchronously loaded data and that `.value` is. So I've changed the references in the Readme to reflect that.
> Correct `.data` references to `.value` in Readme

- addon/tracked-async-data.ts
- type-tests/tracked-async-data-test.ts
As with the `.isPending`, `.isResolved`, and `.isRejected` properties, the value of the `.state` property is known statically, so the exposed types can treat it as a static string.
Additionally, since end users may depend on it in Ember Classic code with dependent keys, like `@computed('someAsyncData.state')`, decorate it with `@dependentKeyCompat`.
> Supply correct types for `state`

- .github/workflows/CI.yml
Run CI also on push to `main`, not only on a pull request.
It *seems* to me the previous config was probably wrong by accident, as there were no CI runs at all for the `main` branch: https://github.com/chriskrycho/ember-async-data/actions/workflows/CI.yml?query=branch%3Amain
> Fix CI config: on push

- README.md
- addon/index.ts
This allows users to switch to a *much* more convenient import:
```js
import { TrackedAsyncData, load } from 'ember-async-data';
```
These are named exports, rather than the default export from the package, to allow for a future default export from the root if we so desire, e.g. if we want a `Resource` to be the default export.
(Note that these are *additional* import paths; the existing paths still work.)
> Add re-export from index

- package.json
- yarn.lock
The standard boilerplate which makes it so releases are just typing `yarn release-it` locally and following the prompts. (Technically that's how I released 0.5.0, but it was using my globally-installed copy of `release-it` instead of one configured for this repo, so it didn't do nice things like automatic CHANGELOG updates or publishing the release on GitHub.)
> Configure release-it for future releases

- .github/workflows/CI.yml
- config/ember-try.js
Update CI config so we run the ember-try compatibility suite and the TS compatibility suite *only once*, and for the supported OS's run *just* `ember test`.
> Chore: only run ember-try suite *once*

- .github/workflows/CI.yml
Requires #151. Pairs with #149 as a breaking change!
> Breaking: drop support for versions of Ember before 3.24 LTS

- addon/tracked-async-data.ts
This shouldn't change the semantics at all; it's just a nice win for the clarity and maintainability of the code, and it guarantees that even if we change it (e.g. to re-`throw`) in the future, it will always end the test waiter.
Thanks to @scalvert for the suggestion!
> Use `finally` for `waiter.endAsync`

- .github/workflows/CI.yml
- README.md
- config/ember-try.js
- package.json
- Add 3.28 LTS to ember-try config.
- Remove versions earlier than 3.28 from CI and support list.
- Update README to specify minimum version
> Set minimum Ember version to 3.28

- README.md
this is similar to https://github.com/chriskrycho/ember-simple-track-helper/pull/103/files, except readme of this package has more content and I'm added note to the are seem most suitable.
another option I considered - create a new "Glint" section next to "Usage > In templates"
> Add Glint usage docs

- .github/workflows/publish-unstable.yml
@chriskrycho would you mind to add `NODE_AUTH_TOKEN` to config to allow such automation?  (I don't have permission)
this will allow folks to use latest changes from `master` as it's not possible to point to branch anymore because it's a monorepo now (which is possible with v1 addons today).
we have similar automation in `ember-modifiers` already
> add publish-unstable workflow

- .github/workflows/publish-unstable.yml
- README.md
- ember-async-data/package.json
- package.json
- test-app/package.json
- yarn.lock
Per https://github.com/embroider-build/addon-blueprint/blob/main/files/__addonLocation__/package.json `engines` field is not needed in the addon package.json as v2 addons don't have any Node.js runtime.
This would safe us from need for major version bump when we need to bump Node for CI compatibility purposes only.
> Remove engines from addon package.json

- ember-async-data/src/tracked-async-data.ts
- Make missing context a hard error in all contexts (not just `assert` for development).
- Make the invalid state checks (looking up `.value` when not `.isResolved` etc.) deprecations, so people can use deprecation workflow to burn them down over time before doing the 2.0 upgrade.
> Add hard error and deprecations for 1.0

- .github/workflows/ci.yml
- README.md
Note sure how what we should consider "old" TypeScript versions.
couldn't get advise in https://rfcs.emberjs.com/id/0724-road-to-typescript/#semantic-versioning-and-supported-typescript-versions either
> Drop TypeScript support for <= 4.7

- README.md
- ember-async-data/src/helpers/load.ts
- ember-async-data/src/tracked-async-data.ts
- ember-async-data/type-tests/load-test.ts
- ember-async-data/type-tests/tracked-async-data-test.ts
- test-app/tests/unit/helpers/load-test.ts
- test-app/tests/unit/tracked-async-data-test.ts
- We had a race condition with the existing waiter teardown, because of an additional, unnecessary, teardown we had in the destructor.
- Considering this also highlighted that we did not need the cache of `Promise`s to `TrackedAsyncData`. The cache had some non-trivial overhead, and it also risked leaking if anything held onto a strong reference to the `Promise`.
This is *breaking*, technically, but is a high-urgency fix so we are treating it as a bugfix.
> Bugfix: drop `context` and stop caching `TrackedAsyncData`

- README.md
- ember-async-data/src/helpers/load.ts
- ember-async-data/src/tracked-async-data.ts
- ember-async-data/type-tests/load-test.ts
- ember-async-data/type-tests/tracked-async-data-test.ts
- test-app/tests/unit/helpers/load-test.ts
- test-app/tests/unit/tracked-async-data-test.ts
Applies the following commits from `main` to `release-0-6-x` with the relevant modifications to account for our switch to a v2 addon:
- 9dac276fe5cd6e203974342abcc3cb658f90084c
- 158c756444d5992e1e9f40778f09de1ff2b04c3d
- d6e3faa15009b15b27b778d7a523b0e195c2d254
- cd0e35840b1af863db516255c8b1379d8e2fd01d
- a14a4620d7a60e1bc242d00a839655143fde07b7
- f1850b3a699e328904d846c75e0a873705e0f814
- e5a01be803a9a99942127f83150743be2da6d4c6
> Backport context bug fix to 0.7.x

- CHANGELOG.md
- README.md
This was made as part of #473 and was part of v1.0.0 release but README.md update was missed
> Update minimum supported Ember.js version

- .github/workflows/ci.yml
- README.md
this is prerequisite for #869, as glint requires TypeScript >=4.8 and some compiled v2 addons include `.ts` extension in `import` statements which is supported since 5.0
> Update TypeScript testing matrix to include >=5.0

- ember-async-data/package.json
is extraneous, and the embroider/auto-import infra know where to get ember-source from.
It's not _wrong_ to include, but it requires folks' manage their deps correctly -- so we can be a little more forgiving to maintainers by just omitting this.
From PR descriptions elsewhere:
- ember-source: removed because the embroider / auto-import know what we intend - it's not bad to have if someone manages their dep graph correctly, which is easier with pnpm, but not everyone gets it right, and folks have a hard time tracking down errors
- @glimmer/tracking removed because it's a real package, but one we don't want to use. This comes up in embroider/vite where the presence of real packages always takes precedence over virtual packages. This is actually problematic because it can break reactivity in …
> Remove unneeded peer dependency declaration

- README.md
- ember-async-data/src/tracked-async-data.ts
`inject` is deprecated, and removing this also helps with global finding `inject` occurrences in `node_modules`.
> Remove use of `inject` in docs
